name: gin_app
# 环境标识
env: dev
# 路由组文件夹名（默认为 router）
routerName: router

server: 
  port: 8000

# redis:
#   host: 127.0.0.1
#   port: 6379
#   password: yuanbao@2018
#   db: 0

# 日志
log:
  # 文件名（不含文件类型）
  filename: gin_app
  # 支持绝对路径（默认路径 linux: /root/logs, win: [basedir]/logs ）
  # filepath: /root/logs

