# 本地 redis
redis:
  addr: 101.133.159.158:6379
  password: "@@@chjiyun"
  db: 0

datasource:
  -
    model: model
    dialect: mysql
    dsn: chjiyun:chjiyun@2020@tcp(101.133.159.158:3306)/egg_test?charset=utf8&parseTime=True&loc=Local

