# 本地 redis
redis:
  addr: 127.0.0.1:6379
  password: yuanbao@2018
  db: 0

datasource:
  -
    model: model
    dialect: mysql
    dsn: U2FsdGVkX18tNHz1t2DfMNtRS7mVKjYb2YXvNPQbm0YVGKjOkgwcmkOMxM9dJ76yuEQ1kRMNf4d582o42IJRcWrySCt8WlMNXGOtUZF5mugtnbj/6IyvWf9FNXFGG5cRkVmCFA2HAGZPbMVrOf0S4Q==

